name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test-bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install -g bats
      - run: bats -v
      - run: echo "Hello WoTest Bash!"
      - run: |
          cd src/webapp/api
          npm install
          npm run test
      - run: |
          cd src/webapp/
          npm install
          npm run test
          cd e2e/cypress/
          npm install
          npm run test
